#!/usr/bin/env bun
// Bakes the OpenCode TUI plugin's source (the entry point plus its whole
// dependency closure) and the dependency pins it needs into a plain
// TypeScript module, src/tui/embedded-plugin-assets.generated.ts, so the
// compiled standalone binary can install the plugin on a machine that has no
// checkout of this repo at all.
//
// Why a generated .ts file of string constants rather than Bun's
// `import x from './file.ts' with { type: 'text' }`: the generated file has
// to stay readable by plain `tsc --noEmit` and vitest on Node, without Bun
// anywhere in the loop. Import attributes over `.ts`-extension specifiers do
// not compose cleanly with TypeScript's own module resolution (the module is
// either unresolvable or resolved as a normal TS module -- i.e. the wrong
// type), and the `declare module '*.ts'` escape hatch would silently
// reinterpret every other .ts import in the codebase. String constants are
// boring and behave identically under tsc, vitest, bun run and
// bun build --compile.
//
// Run it with `make generate-tui-plugin-assets` (Bun lives in the Docker
// toolchain image, not on the host). The generated file is committed, so no
// generation step is needed before a plain `npx tsc --noEmit` / `npx vitest
// run`; tests/tui/install.test.ts re-runs this rendering and diffs it against
// the committed file, so drift fails the suite instead of shipping a stale
// plugin inside the binary.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectPluginAssetsFromDisk, extractRequiredPackageJsonFields, PACKAGE_JSON_SRC_RELATIVE, type PluginAssetFile } from '../src/tui/install.js';

export const GENERATED_FILE_RELATIVE = 'src/tui/embedded-plugin-assets.generated.ts';

export interface EmbeddedPluginAssets {
  assets: PluginAssetFile[];
  dependencies: Record<string, string>;
  scalars: Record<string, unknown>;
}

// Reads everything the embedded install mode needs out of a real checkout,
// through the very same helpers the disk install mode uses -- the plugin
// entry arrives already import-rewritten, so the binary ships exactly what a
// source-mode install would have written.
export function collectEmbeddedPluginAssets(repoRoot: string): EmbeddedPluginAssets {
  const assets = collectPluginAssetsFromDisk(repoRoot);
  const sourcePackageJson = JSON.parse(readFileSync(join(repoRoot, PACKAGE_JSON_SRC_RELATIVE), 'utf-8')) as Record<string, unknown>;
  const { dependencies, scalars } = extractRequiredPackageJsonFields(sourcePackageJson);
  return { assets, dependencies, scalars };
}

// JSON.stringify is the whole escaping strategy: it produces a valid,
// unambiguous double-quoted TS string literal for any input -- backticks,
// ${, backslashes, newlines, unicode -- with none of the pitfalls of
// hand-rolled template-literal escaping.
function literal(value: string): string {
  return JSON.stringify(value);
}

export function renderEmbeddedPluginAssetsModule({ assets, dependencies, scalars }: EmbeddedPluginAssets): string {
  const entries = assets.map((asset) => `  { relativePath: ${literal(asset.relativePath)}, content: ${literal(asset.content)} },`).join('\n');
  return `// AUTO-GENERATED by scripts/generate-tui-plugin-assets.ts -- do not edit by hand.
// Regenerate with \`make generate-tui-plugin-assets\` whenever the TUI plugin
// source, its dependency closure or .opencode/package.json changes;
// tests/tui/install.test.ts fails on drift between this file and the repo.
//
// This is what \`ocstatusline install\` writes when it runs from the compiled
// standalone binary, which has no repo checkout to read the plugin source
// from. Contents are byte-identical to what a source-mode install copies,
// import rewrite included.

export const PLUGIN_ASSET_FILES: Array<{ relativePath: string; content: string }> = [
${entries}
];

export const REQUIRED_PACKAGE_JSON_DEPENDENCIES: Record<string, string> = ${JSON.stringify(dependencies, null, 2)};

export const REQUIRED_PACKAGE_JSON_SCALARS: Record<string, unknown> = ${JSON.stringify(scalars, null, 2)};
`;
}

export function generateEmbeddedPluginAssets(repoRoot: string): { path: string; source: string } {
  const source = renderEmbeddedPluginAssetsModule(collectEmbeddedPluginAssets(repoRoot));
  const path = join(repoRoot, GENERATED_FILE_RELATIVE);
  writeFileSync(path, source, 'utf-8');
  return { path, source };
}

// scripts/generate-tui-plugin-assets.ts -> repo root is one directory up.
// import.meta.url (not Bun's import.meta.dir) so this module also imports
// cleanly under vitest, where the drift check re-uses its rendering.
export const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

if (import.meta.main) {
  const { path, source } = generateEmbeddedPluginAssets(REPO_ROOT);
  process.stdout.write(`generate-tui-plugin-assets: wrote ${path} (${source.length} bytes)\n`);
}
